version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    restart: always
    command: server /data
    volumes:
      - minio:/data
    env_file: dotenv

  minio_console:
    image: minio/console:v0.7.5
    restart: always
    command: server
    env_file: dotenv
    depends_on:
      - minio

  caddy:
    build: ./caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/root/.caddy
    env_file: dotenv
    depends_on:
      - minio
      - minio_console

volumes:
  caddy:
  minio:
